- name : Download SentinelOne installer from master
  win_copy : 
    src: ~/Tools/SentinelOne/SentinelOneWin.exe
    dest: C:\SentinelOneWin.exe

#Ansible thinks the command fails, but it works
- name: Install SentinelOne Agent
  win_shell: "C:\\SentinelOneWin.exe --dont_fail_on_config_preserving_failures -t {{ ansible_token_S1 }}"
  register: output
  ignore_errors: true

- debug: msg="{{ output.stdout }}"
- debug: msg="{{ output.stderr }}"

