- name: Download git installer from master
  win_get_url:
    url: http://192.168.1.52/gitWin64.exe
    dest: 'C:\gitWin64.exe'

- name: Install git
  win_shell: .\gitWin64.exe /SILENT 
  args:
    chdir: 'c:\'
  register: git

- debug: msg="{{ git.stdout }}"

- name: Check if existing DetectionLab directory
  win_stat:
    path: 'c:\DetectionLab'
  register: dir

- name: Git clone Detectionlab
  win_shell: git clone https://github.com/clong/DetectionLab.git
  args:
    chdir: 'c:\'
  register: cloning
  when: not dir.stat.exists

- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Recurse c:\DetectionLab\Vagrant c:\vagrant
  ignore_errors: true

- name: Making Windows10 Great Again
  win_shell:  .\\MakeWindows10GreatAgain.ps1
  args:
    chdir: 'c:\vagrant\scripts'

- name: Remove old join-domain script
  win_shell: rm join-domain.ps1
  args:
    chdir: 'c:\vagrant\scripts\'

- name: Download join-domain script
  win_get_url:
    url: http://192.168.1.52/join-domain.ps1
    dest: 'C:\vagrant\scripts\join-domain.ps1'
  ignore_errors: true

- name: Join the Domain
  win_shell: .\\provision.ps1
  args:
    chdir: 'c:\vagrant\scripts'
  register: join
  ignore_errors: true

- debug: msg="{{ join.stdout }}"
  ignore_errors: true

- name: Update group policy
  win_shell: "gpupdate /force"
  ignore_errors: true

- name: Reboot Server
  win_reboot:
    msg: "Joined the domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60