- name : Download badblood
  win_copy : 
    src: ~/Tools/BadBlood/
    dest: C:\ 
  ignore_errors: true
  
- name: Executing badblood
  win_shell: .\\Invoke-BadBlood.ps1
  args:
    chdir: 'C:\badblood'
  ignore_errors: true