- name : Download badblood
  win_copy : 
    src: ~/Tools/BadBlood/
    dest: C:\ 

- name: Executing badblood
  win_shell: powershell.exe -executionpolicy bypass -noninteractive -File "C:\badblood\Invoke-BadBlood.ps1"