- name: Set hostname to <name>
  hostname:
    name: <name>
  become: yes

- name: Create a directory if it does not exist
  file:
    path: /vagrant
    state: directory
    mode: '0755'
  become: yes

- name: Copy vagrant resources
  synchronize:
    src: ../../Vagrant/resources
    dest: /vagrant/
  become: yes

- name: Create network script
  copy:
    dest: "/tmp/ifcfg-ens35"
    content: |
      TYPE="Ethernet"
        PROXY_METHOD="none"
        BROWSER_ONLY="no"
        BOOTPROTO="static"
        DEFROUTE="yes"
        IPADDR=<HostOnlyIP>
        NETMASK=255.255.255.0
        GATEWAY=<gateway>
        IPV6INIT="no"
        NAME="ens35"
        UUID="1a1f5780-52ed-4c0A-b4b1-d9d564446df2"
        DEVICE="ens35"
        ONBOOT="yes"

- name: Copy file over as root
  shell: "mv /tmp/ifcfg-ens35 /etc/sysconfig/network-scripts/ifcfg-ens35"
  become: yes

- name: Apply new network config
  shell: sudo nmcli con reload
  become: yes

