---

- name: Activate windows
  win_shell: cscript slmgr.vbs /rearm
  args:
    chdir: C:\Windows\System32\

- name: Hostname -> <name>
  win_hostname:
    name: <name>

- name: Reboot
  win_reboot:

- name: Set HostOnly IP Address
  win_shell: netsh int ipv4 set address "Local Area Connection" static <HostOnlyIP> 255.255.255.0 <gateway>
  async: 120
  poll: 0

- name: Set DNS Address
  win_shell: netsh interface ipv4 set dns name="Local Area Connection" static <gateway>
  async: 120
  poll: 0

- name: Download git installer from master
  win_get_url:
    url: http://192.168.1.117/gitWin64.exe
    dest: 'C:\gitWin64.exe'

- name: Install git
  win_shell: .\gitWin64.exe /SILENT 
  args:
    chdir: 'c:\'
  register: git

- name: "Set the TimeZone"
  win_timezone:
    timezone: "Romance Standard Time"
