- name : Download UMCA4 installer from master
  win_copy : 
    src: ~/Tools/UMCA4/UcmaRuntimeSetup.exe
    dest: C:\UcmaRuntimeSetup.exe

- name: Install UMCA4 
  win_shell: "C:\\UcmaRuntimeSetup.exe /passive /norestart"
  register: output
  ignore_errors: true

- name: Check if existing directory
  win_stat:
    path: 'c:\lab-deploy'
  register: dir

- name: Git clone repository
  win_shell: git clone https://github.com/heraclesadv/lab-deploy.git
  args:
    chdir: 'c:\'
  register: cloning
  when: not dir.stat.exists

- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Recurse c:\lab-deploy\Vagrant c:\vagrant
  ignore_errors: true

- name: Making Windows10 Great Again
  win_shell:  .\\MakeWindows10GreatAgain.ps1
  args:
    chdir: 'c:\vagrant\scripts'

- name: Join the Domain
  win_shell: .\\provision.ps1 <DCIP>
  args:
    chdir: 'c:\vagrant\scripts'
  register: join
  ignore_errors: true

- debug: msg="{{ join.stdout }}"
  ignore_errors: true

- name: Update group policy
  win_shell: "gpupdate /force"
  ignore_errors: true

- name: "Set the TimeZone"
  win_timezone:
    timezone: "Romance Standard Time"

- name: Reboot Server
  win_reboot:
    msg: "Joined the domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60
  ignore_errors: true

- name: Install Exchange Prereqs
  win_shell: .\\install-exchange-prerequisites.ps1
  args:
    chdir: 'c:\vagrant\scripts'
  register: exchange_prereqs
  changed_when: "'A reboot is required to continue installation of exchange.' in exchange_prereqs.stdout"

- name: Reboot After Installing Exchange PreReqs
  win_reboot:
    msg: "Exchange Prereqs installed. Rebooting..."
    pre_reboot_delay: 5
    reboot_timeout: 600
    post_reboot_delay: 60

- name: Make Exchange Directory
  win_file:
    path: 'C:\exchange2016'
    state: directory

- name: Download ISO
  win_get_url:
    url: 'https://download.microsoft.com/download/2/5/8/258D30CF-CA4C-433A-A618-FB7E6BCC4EEE/ExchangeServer2016-x64-cu12.iso'
    dest: 'C:\exchange2016\ExchangeServer2016-x64-cu12.iso'

- name: Ensure an ISO is mounted
  win_disk_image:
    image_path: 'C:\exchange2016\ExchangeServer2016-x64-cu12.iso'
    state: present
  register: disk_image_out

- name: Prepare Schema
  win_package:
    path: '{{ disk_image_out.mount_paths[0] }}Setup.exe'
    arguments: >-
      /IAcceptExchangeServerLicenseTerms
      /PrepareSchema
    product_id: '{CD981244-E9B8-405A-9026-6AEB9DCEF1F1}'
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: WINDOMAIN.local\Administrator
    ansible_become_password: vagrant
  register: prepare_schema

- name: Prepare AD
  win_package:
    path: '{{ disk_image_out.mount_paths[0] }}Setup.exe'
    arguments: >-
      /IAcceptExchangeServerLicenseTerms
      /PrepareAD
      /OrganizationName: DetectionLab
    product_id: '{CD981244-E9B8-405A-9026-6AEB9DCEF1F1}'
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: WINDOMAIN.local\Administrator
    ansible_become_password: vagrant
  register: prepare_ad

- name: Install Exchange
  win_package:
    path: '{{ disk_image_out.mount_paths[0] }}Setup.exe'
    arguments: >-
      /IAcceptExchangeServerLicenseTerms
      /Mode:Install
      /Role:Mailbox
    product_id: '{CD981244-E9B8-405A-9026-6AEB9DCEF1F1}'
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: WINDOMAIN.local\Administrator
    ansible_become_password: vagrant
  register: install_exchange

- name: Reboot after Exchange Installation
  win_reboot:
    msg: "Exchange installed. Rebooting..."
    pre_reboot_delay: 5
    reboot_timeout: 600
    post_reboot_delay: 60

- name: Clear Event Logs
  win_shell: "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"
