---

- name: Set hostname to <name>
  hostname:
    name: <name>
  become: yes

- name: Create a directory if it does not exist
  file:
    path: /vagrant
    state: directory
    mode: '0755'
  become: yes

- name: Copy vagrant resources
  synchronize:
    src: ../../Vagrant/resources
    dest: /vagrant/
  become: yes

- name: changing network config
  shell: mv /etc/network/temporary /etc/network/interfaces
  become: yes

- name: set new ip
  shell: sudo sed -i -e 's/address/address <HostOnlyIP>/' /etc/network/interfaces
  become: yes

- name: set new gateway
  shell: sudo sed -i -e 's/gateway/gateway <gateway>/' /etc/network/interfaces
  become: yes

- name: switch on eth0
  shell: "sudo ifup eth0"
  become: yes

- name: updater etc hosts
  shell: "printf '127.0.0.1        <name>' | sudo tee -a /etc/hosts"
  become: yes

- name: add DNS adress
  shell: "printf 'nameserver <gateway>\n' | sudo tee /etc/resolv.conf"
  become: yes

- name: rename tightVNC file according to new hostname
  shell: mv /home/vagrant/.vnc/kali:1.log /home/vagrant/.vnc/<name>:1.log && mv /home/vagrant/.vnc/kali:1.pid /home/vagrant/.vnc/<name>:1.pid
  become: yes

- name: update tightVNC file timestamp 
  shell: "printf '#!/bin/bash\ntouch /home/vagrant/.vnc/<name>:1.pid\n' | sudo tee /usr/bin/vnc_script"
  become: yes

- name: start tightVNC
  shell: tightvncserver
