---

- name: Set hostname to <name>
  hostname:
    name: <name>
  become: yes

- name: Create a directory if it does not exist
  file:
    path: /vagrant
    state: directory
    mode: '0755'
  become: yes

- name: Copy vagrant resources
  synchronize:
    src: ../../Vagrant/resources
    dest: /vagrant/
  become: yes

- name: Create netplan file
  copy:
    dest: "/tmp/01-netcfg.yaml"
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: true
          eth1:
            dhcp4: false
            addresses: [<HostOnlyIP>/24]
            gateway4: <gateway>
            nameservers:
              addresses: [<gateway>, <gateway>]

- name: Copy the netplan file over as root
  shell: "mv /tmp/01-netcfg.yaml /etc/netplan/01-netcfg.yaml"
  become: yes

- name: Apply the new netplan
  shell: netplan apply
  become: yes


# The lines below create and apply a new netplan at next startup, because the lan nic will be removed
# and it tries dhcp on hsot only, which is bad
- name: Create second netplan file
  copy:
    dest: "/tmp/01-netcfg.yaml"
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: false
            addresses: [<HostOnlyIP>/24]
            gateway4: <gateway>
            nameservers:
              addresses: [<gateway>, <gateway>]

- name: Copy the netplan file over as root
  shell: "mv /tmp/01-netcfg.yaml /etc/netplan/01-netcfg.yaml"
  become: yes

- name: Create script
  copy:
    dest: "/tmp/startup.sh"
    content: |
      netplan apply

- name: Chmod the script
  shell: "chmod +x /tmp/startup.sh"
  become: yes

- name: Add the crontab
  ansible.builtin.cron:
    name: "bar"
    special_time: reboot
    job: " /tmp/startup.sh"
    user: root
  become: true
