---

- name: Rearm windows license
  win_shell: cscript //B "%windir%\system32\slmgr.vbs" /rearmn
  register: bwaaa
  ignore_errors: true

- debug: msg="{{ bwaaa.stdout }}"
- debug: msg="{{ bwaaa.stderr }}"

- name: Reboot
  win_reboot:

- name: Hostname -> <name>
  win_hostname:
    name: <name>

- name: Reboot
  win_reboot:

- name: Set HostOnly IP Address
  win_command: netsh int ip set address name="Connexion au réseau local 2" static <HostOnlyIP> 255.255.255.0 <gateway>
 
- name: Set DNS
  win_command: netsh interface ip set dns name="Connexion au réseau local 2" static <DNSServer> primary

- name: Download git installer from master
  win_get_url:
    url: http://192.168.1.52/gitWin64.exe
    dest: 'C:\gitWin64.exe'

- name: Install git
  win_shell: .\gitWin64.exe /SILENT 
  args:
    chdir: 'c:\'
  register: git

- debug: msg="{{ git.stdout }}"

