
- name: Install tools 
  args: 
    executable: /bin/bash
  become: yes
  shell: |
      apt update
      apt install -y jq whois build-essential git mysql-server redis-server python3-pip unzip htop libcairo2-dev libjpeg-turbo8-dev libpng-dev libtool-bin libossp-uuid-dev libavcodec-dev libavutil-dev libswscale-dev freerdp2-dev libpango1.0-dev libssh2-1-dev libvncserver-dev libtelnet-dev libssl-dev libvorbis-dev libwebp-dev tomcat9 tomcat9-admin tomcat9-user tomcat9-common

- name: Install Guacamole
  args: 
    executable: /bin/bash
  become: yes
  shell: | 
    echo "[$(date +%H:%M:%S)]: Setting up Guacamole..."
    cd /opt || exit 1
    echo "[$(date +%H:%M:%S)]: Downloading Guacamole..."
    wget --progress=bar:force "https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download" -O guacamole-server-1.3.0.tar.gz
    tar -xf guacamole-server-1.3.0.tar.gz && cd guacamole-server-1.3.0 || echo "[-] Unable to find the Guacamole folder."
    echo "[$(date +%H:%M:%S)]: Configuring Guacamole and running 'make' and 'make install'..."
    ./configure --with-init-dir=/etc/init.d && make --quiet &>/dev/null && make --quiet install &>/dev/null || echo "[-] An error occurred while installing Guacamole."
    ldconfig
    cd /var/lib/tomcat9/webapps || echo "[-] Unable to find the tomcat9/webapps folder."
    wget --progress=bar:force "https://apache.org/dyn/closer.lua/guacamole/1.3.0/binary/guacamole-1.3.0.war?action=download" -O guacamole.war
    mkdir /etc/guacamole
    mkdir /etc/guacamole/shares
    sudo chmod 777 /etc/guacamole/shares
    mkdir /usr/share/tomcat9/.guacamole
    cp /vagrant/resources/guacamole/user-mapping.xml /etc/guacamole/
    cp /vagrant/resources/guacamole/guacamole.properties /etc/guacamole/
    cp /vagrant/resources/guacamole/guacd.service /lib/systemd/system
    sudo ln -s /etc/guacamole/guacamole.properties /usr/share/tomcat9/.guacamole/
    sudo ln -s /etc/guacamole/user-mapping.xml /usr/share/tomcat9/.guacamole/
    # Thank you Kifarunix: https://kifarunix.com/install-guacamole-on-debian-11/
    useradd -M -d /var/lib/guacd/ -r -s /sbin/nologin -c "Guacd User" guacd
    mkdir /var/lib/guacd
    chown -R guacd: /var/lib/guacd
    systemctl daemon-reload
    systemctl enable guacd
    systemctl enable tomcat9
    systemctl start guacd
    systemctl start tomcat9
    echo "[$(date +%H:%M:%S)]: Guacamole installation complete!"
  register: install_guacamole