- name : Download Harfang installer from master
  win_copy : 
    src: ~/Tools/Harfang/harfangWin.msi
    dest: C:\harfangWin.msi

- name: Install Harfang Agent
  win_shell: "msiexec /qn /i C:\\harfangWin.msi HOST=639eb439a1003034.hurukai.io PORT=443 PROTO=https KEY={{ ansible_token_harfang }}"
  register: output
  ignore_errors: true

- debug: msg="{{ output.stdout }}"
- debug: msg="{{ output.stderr }}"

