- name: Install SentinelOne agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    wget "http://192.168.1.52/SentinelOneUbuntu.deb"
    dpkg -i SentinelOneUbuntu.deb
    /opt/sentinelone/bin/sentinelctl management token set {{ ansible_token_S1 }}
    /opt/sentinelone/bin/sentinelctl control start
  register: sone

- debug: msg="{{ sone.stdout }}"
  ignore_errors: true