- name : copy SentinelOne
  become : true
  copy : 
    src: ~/Tools/SentinelOne/SentinelOneUbuntu.deb
    dest: /etc/SentinelOneUbuntu.deb

- name: Install SentinelOne agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    dpkg -i /etc/SentinelOneUbuntu.deb
    /opt/sentinelone/bin/sentinelctl management token set {{ ansible_token_S1 }}
    /opt/sentinelone/bin/sentinelctl control start
  register: sone

- debug: msg="{{ sone.stdout }}"
  ignore_errors: true