- name: Install SentinelOne agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    wget "http://192.168.1.52/SentinelOneUbuntu.deb"
    dpkg -i SentinelOneUbuntu.deb
    /opt/sentinelone/bin/sentinelctl management token set eyJ1cmwiOiAiaHR0cHM6Ly9hZHZlbnMuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogIjg2ZjNhZDI1MDdkYTQxODQifQ==
    /opt/sentinelone/bin/sentinelctl control start
  register: sone

- debug: msg="{{ sone.stdout }}"
  ignore_errors: true