- name : copy CybereasonLinux.deb
  become : true
  copy : 
    src: ~/Tools/Cybereason/CybereasonLinux.deb
    dest: /etc/CybereasonLinux.deb

- name: Install Cybereason agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    sudo apt install gdb -y
    sudo dpkg -i /etc/CybereasonLinux.deb
  register: cbrs

- debug: msg="{{ cbrs.stdout }}"
  ignore_errors: true