- name : copy harfangUbuntu.deb
  become : true
  copy : 
    src: ~/Tools/Harfang/harfangUbuntu.deb
    dest: /etc/harfangUbuntu.deb

- name: Install HarfangLab agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    DEBIAN_FRONTEND=noninteractive HURUKAI_HOST=639eb439a1003034.hurukai.io HURUKAI_PORT=443 HURUKAI_PROTOCOL=https HURUKAI_KEY={{ ansible_token_harfang }} apt install /etc/harfangUbuntu.deb
  register: hrfg

- debug: msg="{{ hrfg.stdout }}"
  ignore_errors: true