- name: Install HarfangLab agent on ubuntu
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    wget "http://192.168.1.52/harfangUbuntu.deb"
    DEBIAN_FRONTEND=noninteractive HURUKAI_HOST=639eb439a1003034.hurukai.io HURUKAI_PORT=443 HURUKAI_PROTOCOL=https HURUKAI_KEY=4510601d3db263c2a292c80e2205c78b9839030b29b4047fc5558b82b27a8f69 apt install ./harfangUbuntu.deb
  register: hrfg

- debug: msg="{{ hrfg.stdout }}"
  ignore_errors: true