- name : Download Cybereason installer from master
  win_copy : 
    src: ~/Tools/Cybereason/CybereasonWindows.exe
    dest: C:\CybereasonWindows.exe

- name: Install Cybereason Agent
  win_shell: "C:\\CybereasonWindows.exe /install /quiet /norestart "
  register: output
  ignore_errors: true

- debug: msg="{{ output.stdout }}"
- debug: msg="{{ output.stderr }}"

